import type { RuntimeExecutor, RuntimeRequest, RuntimeResponse, SkillStructuredOutput } from "../contract/types.js";

export class StubRuntimeExecutor implements RuntimeExecutor {
  constructor(
    private readonly label = "stub",
    private readonly output?: Partial<SkillStructuredOutput>,
  ) {}

  async execute(request: RuntimeRequest): Promise<RuntimeResponse> {
    const structured: SkillStructuredOutput = {
      artifactMarkdown: this.output?.artifactMarkdown
        ?? `# ${request.runtime} ${this.label} artifact\n\nGenerated by stub runtime executor for pilot testing.`,
      artifactRelativePath: this.output?.artifactRelativePath ?? "stub-artifact.md",
      selfCheck: this.output?.selfCheck ?? { result: "pass", messages: ["stub self-check passed"] },
      findings: this.output?.findings ?? [],
      traceSuggestions: this.output?.traceSuggestions ?? [],
    };
    return {
      status: "success",
      modelId: request.modelId ?? `${request.runtime}-stub`,
      structuredOutput: structured,
    };
  }
}
